name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: actions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/learning-devops
            git pull
            docker build -t minha-aplicacao .
            docker stop minha-aplicacao || true
            docker rm minha-aplicacao || true
            docker run -d --name minha-aplicacao -p 80:80 minha-aplicacao